import React from 'react';
import { CheckCircle2, Download, ReceiptText, RotateCcw, X } from 'lucide-react';
import { money, dateTime } from '../utils/format';

export default function TransactionStatementModal({ transaction, walletAddress, user, onClose, onRedo }) {
  const isDeposit = transaction.type === 'DEPOSIT';
  const isInitialAllocation = transaction.type === 'SYSTEM_INITIALIZATION';
  const isSender = transaction.sourceAddress === walletAddress;
  const outgoing = isSender && !isDeposit;
  const counterparty = isSender ? transaction.destinationAddress : transaction.sourceAddress;
  const counterpartyUsername = isSender ? transaction.destinationUsername : transaction.sourceUsername;
  const counterpartyDisplay = counterpartyUsername ? `@${counterpartyUsername} (${counterparty})` : counterparty;
  const counterpartyName = isSender ? transaction.destinationName : transaction.sourceName;
  const direction = isInitialAllocation ? 'Initial demo balance received' : (isDeposit ? 'Deposit received' : (outgoing ? 'Transfer sent' : 'Transfer received'));
  const currency = transaction.currency || 'YUG';
  const hasCounterparty = !isDeposit && !isInitialAllocation;

  const downloadStatement = () => {
    const canvas = document.createElement('canvas');
    canvas.width = 1400;
    canvas.height = 1700;
    const ctx = canvas.getContext('2d');
    let y = 120;
    const text = (value, size, color, weight = '400') => {
      ctx.fillStyle = color;
      ctx.font = `${weight} ${size}px Arial, sans-serif`;
      ctx.fillText(String(value), 100, y);
      y += size + 26;
    };
    const row = (label, value) => {
      ctx.fillStyle = '#94a3b8'; ctx.font = '500 28px Arial, sans-serif'; ctx.fillText(label, 100, y);
      ctx.fillStyle = '#f8fafc'; ctx.font = '700 27px monospace'; ctx.fillText(String(value), 510, y);
      y += 70; ctx.strokeStyle = '#334155'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(100, y - 23); ctx.lineTo(1300, y - 23); ctx.stroke();
    };

    ctx.fillStyle = '#111827'; ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.fillStyle = '#10b981'; ctx.fillRect(0, 0, 1400, 24);
    text('YugCoin', 54, '#f8fafc', '700');
    text('Payment Receipt', 32, '#94a3b8', '600'); y += 30;
    text(`${outgoing ? '-' : '+'}${money(transaction.amount)} ${currency}`, 56, outgoing ? '#fda4af' : '#86efac', '700'); y += 25;
    row('Status', transaction.status || 'COMPLETED');
    row('Date & time', dateTime(transaction.createdAt));
    row(outgoing ? 'To' : 'From', counterpartyDisplay || '—');
    if (counterpartyName) row(outgoing ? 'Recipient name' : 'Sender name', counterpartyName);
    row('Amount', `${money(transaction.amount)} ${currency}`);
    row('Fee', `${money(transaction.fee)} ${currency}`);
    row('Total', `${money(Number(transaction.amount || 0) + Number(transaction.fee || 0))} ${currency}`);
    row('Reference', transaction.description || '—');
    row('Transaction ID', transaction.transactionId || '—');
    ctx.fillStyle = '#94a3b8'; ctx.font = '500 22px Arial, sans-serif'; ctx.fillText('Generated by YugCoin Wallet', 100, 1600);

    const link = document.createElement('a');
    link.download = `yugcoin-receipt-${transaction.transactionId || 'transaction'}.jpeg`;
    link.href = canvas.toDataURL('image/jpeg', 0.95);
    link.click();
  };

  return (
    <div className="modal-overlay statement-overlay" role="dialog" aria-modal="true" aria-labelledby="statement-title">
      <div className="modal-content statement-modal">
        <div className="flex justify-between items-center gap-4">
          <div className="flex items-center gap-3">
            <div className="statement-icon"><ReceiptText size={19} /></div>
            <div>
              <h3 id="statement-title" className="font-extrabold" style={{ fontSize: '1.2rem' }}>{direction}</h3>
              <span className="statement-id">Ref {transaction.transactionId}</span>
            </div>
          </div>
          <button type="button" className="scanner-close" onClick={onClose} aria-label="Close receipt"><X size={17} /></button>
        </div>

        <div className="statement-summary">
          <div className="statement-amount" data-negative={outgoing} style={{ border: 'none', background: 'transparent', padding: 0 }}>
            <strong style={{ fontSize: '2.2rem', color: outgoing ? 'var(--danger)' : 'var(--primary)' }}>
              {outgoing ? '\u2212' : '+'}{money(transaction.amount)} {currency}
            </strong>
            <span style={{ color: 'var(--text-muted)', fontWeight: 600 }}>{direction}</span>
          </div>
          <div className="statement-status"><CheckCircle2 size={18} /> {transaction.status || 'COMPLETED'}</div>
        </div>

        <dl className="statement-details">
          <div><dt>{outgoing ? 'To' : (hasCounterparty ? 'From' : 'Credited to')}</dt><dd>{counterpartyDisplay || (walletAddress || '—')}</dd></div>
          {counterpartyName && <div><dt>Name</dt><dd>{counterpartyName}</dd></div>}
          <div><dt>Date & time</dt><dd>{dateTime(transaction.createdAt)}</dd></div>
          <div><dt>Amount</dt><dd>{money(transaction.amount)} {currency}</dd></div>
          <div><dt>Fee</dt><dd>{Number(transaction.fee) > 0 ? `${money(transaction.fee)} ${currency}` : 'Free'}</dd></div>
          <div className="statement-total"><dt>Total</dt><dd>{money(Number(transaction.amount || 0) + Number(transaction.fee || 0))} {currency}</dd></div>
          {transaction.description && <div><dt>Reference</dt><dd>{transaction.description}</dd></div>}
        </dl>

        <div className="statement-actions">
          <button type="button" className="liquid-btn-primary flex items-center justify-center gap-2" onClick={downloadStatement} style={{ padding: '0.9rem', flex: 1 }}><Download size={18} /> Download receipt</button>
          {outgoing && onRedo && <button type="button" className="liquid-btn-secondary flex items-center justify-center gap-2" onClick={() => onRedo({ destinationAddress: counterpartyUsername ? `@${counterpartyUsername}` : counterparty, amount: String(transaction.amount), description: transaction.description || '' })} style={{ padding: '0.8rem', flex: 1 }}><RotateCcw size={17} /> Send again</button>}
        </div>
      </div>
    </div>
  );
}
