import React from 'react';
import { CheckCircle2, Download, ReceiptText, RotateCcw, X } from 'lucide-react';

const amount = (value) => Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 4 });
const dateTime = (value) => new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });

export default function TransactionStatementModal({ transaction, walletAddress, onClose, onRedo }) {
  const isDeposit = transaction.type === 'DEPOSIT';
  const isSender = transaction.sourceAddress === walletAddress;
  const outgoing = isSender && !isDeposit;
  const counterparty = isSender ? transaction.destinationAddress : transaction.sourceAddress;
  const direction = isDeposit ? 'Deposit received' : (outgoing ? 'Transfer sent' : 'Transfer received');
  const currency = transaction.currency || 'YUG';

  const downloadStatement = () => {
    const canvas = document.createElement('canvas');
    canvas.width = 1400;
    canvas.height = 1160;
    const ctx = canvas.getContext('2d');
    let y = 110;
    const text = (value, size, color, weight = '400') => {
      ctx.fillStyle = color;
      ctx.font = `${weight} ${size}px Arial, sans-serif`;
      ctx.fillText(String(value), 100, y);
      y += size + 26;
    };
    const row = (label, value) => {
      ctx.fillStyle = '#64748b'; ctx.font = '500 28px Arial, sans-serif'; ctx.fillText(label, 100, y);
      ctx.fillStyle = '#0f172a'; ctx.font = '700 27px monospace'; ctx.fillText(String(value), 510, y);
      y += 70; ctx.strokeStyle = '#e2e8f0'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(100, y - 23); ctx.lineTo(1300, y - 23); ctx.stroke();
    };

    ctx.fillStyle = '#f8fafc'; ctx.fillRect(0, 0, 1400, 1160);
    ctx.fillStyle = '#0f172a'; ctx.fillRect(0, 0, 1400, 24);
    text('YugCoin', 54, '#0f172a', '700');
    text('Transaction Statement', 32, '#475569', '600'); y += 30;
    text(direction, 36, '#0369a1', '700');
    text(`${outgoing ? '-' : '+'}${amount(transaction.amount)} ${currency}`, 50, outgoing ? '#e11d48' : '#059669', '700'); y += 25;
    row('Transaction ID', transaction.transactionId || '—');
    row('Status', transaction.status || 'COMPLETED');
    row('Date & time', dateTime(transaction.createdAt));
    row(outgoing ? 'Recipient' : 'Sender', counterparty || '—');
    row('Amount', `${amount(transaction.amount)} ${currency}`);
    row('Fee', `${amount(transaction.fee)} ${currency}`);
    row('Reference', transaction.description || '—');
    ctx.fillStyle = '#64748b'; ctx.font = '500 22px Arial, sans-serif'; ctx.fillText('Generated by YugCoin Wallet', 100, 1080);

    const link = document.createElement('a');
    link.download = `yugcoin-statement-${transaction.transactionId || 'transaction'}.jpeg`;
    link.href = canvas.toDataURL('image/jpeg', 0.95);
    link.click();
  };

  return (
    <div className="modal-overlay" role="dialog" aria-modal="true" aria-labelledby="statement-title">
      <div className="modal-content statement-modal">
        <div className="flex justify-between items-center gap-4">
          <div className="flex items-center gap-3"><div className="statement-icon"><ReceiptText size={19} /></div><div><h3 id="statement-title" className="font-extrabold" style={{ fontSize: '1.25rem' }}>Transaction Statement</h3><span className="statement-id">{transaction.transactionId}</span></div></div>
          <button type="button" className="scanner-close" onClick={onClose} aria-label="Close statement"><X size={17} /></button>
        </div>
        <div className="statement-status"><CheckCircle2 size={18} /> {transaction.status || 'COMPLETED'}</div>
        <div className="statement-amount" data-negative={outgoing}><span>{direction}</span><strong>{outgoing ? '-' : '+'}{amount(transaction.amount)} {currency}</strong></div>
        <dl className="statement-details">
          <div><dt>Date & time</dt><dd>{dateTime(transaction.createdAt)}</dd></div>
          <div><dt>{outgoing ? 'Recipient' : 'Sender'}</dt><dd>{counterparty || '—'}</dd></div>
          <div><dt>Amount</dt><dd>{amount(transaction.amount)} {currency}</dd></div>
          <div><dt>Fee</dt><dd>{amount(transaction.fee)} {currency}</dd></div>
          <div><dt>Reference</dt><dd>{transaction.description || '—'}</dd></div>
        </dl>
        <button type="button" className="liquid-btn-primary flex items-center justify-center gap-2" onClick={downloadStatement} style={{ padding: '0.9rem' }}><Download size={18} /> Download as JPEG</button>
        {transaction.type === 'TRANSFER' && onRedo && <button type="button" className="liquid-btn-secondary flex items-center justify-center gap-2" onClick={() => onRedo({ destinationAddress: counterparty, amount: String(transaction.amount), description: transaction.description || '' })} style={{ padding: '0.8rem' }}><RotateCcw size={17} /> Redo payment</button>}
      </div>
    </div>
  );
}
