import React, { useEffect, useState } from 'react';

const API = process.env.REACT_APP_API_URL || 'https://yugcoin-backend.onrender.com/api';
const request = async (path, token, options = {}) => {
  const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...options.headers } });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Request failed.');
  return data;
};

export default function App() {
  const [token, setToken] = useState(() => localStorage.getItem('yugcoin_admin_token') || '');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [error, setError] = useState(''); const [overview, setOverview] = useState(null); const [users, setUsers] = useState([]); const [coupons, setCoupons] = useState([]); const [transactions, setTransactions] = useState([]); const [search, setSearch] = useState('');
  const [coupon, setCoupon] = useState({ code: '', valueAmount: '', description: '', expiresAt: '' });
  const load = async () => { try { const [o, u, c, t] = await Promise.all([request('/admin/overview', token), request('/admin/users', token), request('/admin/coupons', token), request('/admin/transactions', token)]); setOverview(o.overview); setUsers(u.users); setCoupons(c.coupons); setTransactions(t.transactions); setError(''); } catch (err) { setError(err.message); } };
  useEffect(() => { if (token) load(); }, [token]);
  const login = async (event) => { event.preventDefault(); try { const response = await request('/auth/login', '', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); localStorage.setItem('yugcoin_admin_token', response.token); setToken(response.token); } catch (err) { setError(err.message); } };
  const setWalletStatus = async (walletId, status) => { await request(`/admin/wallets/${walletId}`, token, { method: 'PATCH', body: JSON.stringify({ status }) }); load(); };
  const changeRole = async (userId, role) => { await request(`/admin/users/${userId}`, token, { method: 'PATCH', body: JSON.stringify({ role }) }); load(); };
  const createCoupon = async (event) => { event.preventDefault(); try { await request('/admin/coupons', token, { method: 'POST', body: JSON.stringify(coupon) }); setCoupon({ code: '', valueAmount: '', description: '', expiresAt: '' }); load(); } catch (err) { setError(err.message); } };
  const toggleCoupon = async (item) => { await request(`/admin/coupons/${item._id}`, token, { method: 'PATCH', body: JSON.stringify({ status: item.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE' }) }); load(); };
  if (!token) return <main className="login"><form onSubmit={login}><h1>YugCoin Admin</h1><p>Administrator access only.</p>{error && <div className="error">{error}</div>}<input type="email" placeholder="Admin email" value={email} onChange={(e) => setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={(e) => setPassword(e.target.value)} required/><button>Sign in</button></form></main>;
  const filteredUsers = users.filter((user) => `${user.name} ${user.email} ${user.username} ${user.walletAddress}`.toLowerCase().includes(search.toLowerCase()));
  return <main className="admin-shell"><header><div><small>YugCoin control center</small><h1>Administration</h1><p>Manage the learning wallet with protected controls.</p></div><button onClick={() => { localStorage.removeItem('yugcoin_admin_token'); setToken(''); }}>Sign out</button></header>{error && <div className="error">{error}</div>}{overview && <section className="stats"><article><b>{overview.users}</b><span>Accounts</span></article><article><b>{overview.wallets}</b><span>YUG wallets</span></article><article><b>{overview.yugInWallets.toLocaleString()}</b><span>YUG in wallets</span></article><article><b>{overview.activeCoupons}</b><span>Active coupons</span></article></section>}<section><div className="section-head"><div><h2>Accounts</h2><p>Role and wallet access controls.</p></div><input className="search" placeholder="Search name, email, username, or wallet" value={search} onChange={(e) => setSearch(e.target.value)}/></div><div className="users">{filteredUsers.map((user) => <article key={user.id}><div><strong>{user.name}</strong><span>{user.email}</span><span>@{user.username} · {user.walletAddress}</span></div><label>Role<select value={user.role} onChange={(e) => changeRole(user.id, e.target.value)}><option>USER</option><option>ADMIN</option></select></label><div className="wallets">{user.wallets.filter((wallet) => wallet.currency === 'YUG').map((wallet) => <div key={wallet._id}><span>YUG {wallet.balance}</span><button onClick={() => setWalletStatus(wallet._id, wallet.status === 'ACTIVE' ? 'FROZEN' : 'ACTIVE')}>{wallet.status === 'ACTIVE' ? 'Freeze' : 'Activate'}</button></div>)}</div></article>)}</div></section><section className="coupon-section"><div><h2>YUG coupons</h2><p>Create and control coupon values in YUG.</p></div><form onSubmit={createCoupon}><input placeholder="Code e.g. YUG-100" value={coupon.code} onChange={(e) => setCoupon({ ...coupon, code: e.target.value.toUpperCase() })} required/><input type="number" min="1" placeholder="Value in YUG" value={coupon.valueAmount} onChange={(e) => setCoupon({ ...coupon, valueAmount: e.target.value })} required/><input placeholder="Description" value={coupon.description} onChange={(e) => setCoupon({ ...coupon, description: e.target.value })}/><input type="date" value={coupon.expiresAt} onChange={(e) => setCoupon({ ...coupon, expiresAt: e.target.value })}/><button>Create coupon</button></form><div className="coupons">{coupons.map((item) => <article key={item._id}><strong>{item.code}</strong><span>YUG {item.valueAmount}</span><span>{item.status}</span><button onClick={() => toggleCoupon(item)}>{item.status === 'ACTIVE' ? 'Disable' : 'Enable'}</button></article>)}</div></section><section><h2>Latest YUG activity</h2><div className="activity">{transactions.slice(0, 8).map((tx) => <div key={tx._id}><strong>{tx.type}</strong><span>{tx.amount} YUG</span><span>{new Date(tx.createdAt).toLocaleString()}</span></div>)}</div></section></main>;
}
