import React, { useEffect, useState } from 'react';

const API = process.env.REACT_APP_API_URL || 'https://yugcoin-backend.onrender.com/api';
const call = async (path, token, options = {}) => { const r = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type':'application/json', ...(token ? { Authorization:`Bearer ${token}` } : {}), ...options.headers } }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Request failed'); return d; };
export default function App() {
 const [token,setToken]=useState(()=>localStorage.getItem('yugcoin_admin_token')||''); const [tab,setTab]=useState('dashboard'); const [email,setEmail]=useState(()=>localStorage.getItem('yugcoin_admin_email')||''); const [password,setPassword]=useState(''); const [show,setShow]=useState(false); const [remember,setRemember]=useState(Boolean(localStorage.getItem('yugcoin_admin_email'))); const [data,setData]=useState({}); const [error,setError]=useState('');
 const load=async()=>{try{const [o,u,t,c]=await Promise.all(['/admin/overview','/admin/users','/admin/transactions','/admin/coupons'].map(p=>call(p,token)));setData({overview:o.overview,users:u.users,transactions:t.transactions,coupons:c.coupons});}catch(e){setError(e.message)}}; useEffect(()=>{if(token)load()},[token]);
 const login=async e=>{e.preventDefault();try{const r=await call('/auth/login','',{method:'POST',body:JSON.stringify({email,password})});if(remember)localStorage.setItem('yugcoin_admin_email',email);else localStorage.removeItem('yugcoin_admin_email');localStorage.setItem('yugcoin_admin_token',r.token);setToken(r.token)}catch(e){setError(e.message)}};
 if(!token)return <main className="login"><form onSubmit={login}><small>YugCoin control center</small><h1>Admin access</h1><p>Manage the YugCoin learning wallet securely.</p>{error&&<div className="error">{error}</div>}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email" required/><div className="password-row"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" required/><button type="button" onClick={()=>setShow(!show)}>{show?'Hide':'Show'}</button></div><label className="remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>Remember me</label><button>Sign in to dashboard</button></form></main>;
 const nav=['dashboard','transactions','accounts','coupons','profile','open-source']; const content=tab==='dashboard'?<><section className="stats">{Object.entries(data.overview||{}).map(([k,v])=><article key={k}><b>{v}</b><span>{k.replace(/([A-Z])/g,' $1')}</span></article>)}</section><section><h2>Admin panel</h2><p>Live controls, account protection, YUG wallet oversight, and coupon management.</p></section></>:tab==='transactions'?<section><h2>YUG transactions</h2><div className="activity">{(data.transactions||[]).map(x=><div key={x._id}><strong>{x.sourceName} → {x.destinationName}</strong><span>{x.amount} YUG</span><span>{new Date(x.createdAt).toLocaleString()}</span></div>)}</div></section>:tab==='accounts'?<section><h2>Account controls</h2><div className="users">{(data.users||[]).map(u=><article key={u.id}><strong>{u.name}</strong><span>{u.email}</span><span>@{u.username} · {u.walletAddress}</span></article>)}</div></section>:<section><h2>{tab.replace('-',' ')}</h2><p>Administrator-only YugCoin workspace. Use the dashboard to monitor controls and the transaction page to review wallet activity.</p></section>;
 return <main className="admin-shell"><header><div><small>YugCoin administration</small><h1>Control dashboard</h1><p>Protected YUG wallet operations.</p></div><button onClick={()=>{localStorage.removeItem('yugcoin_admin_token');setToken('')}}>Sign out</button></header><nav className="admin-nav">{nav.map(x=><button key={x} onClick={()=>setTab(x)}>{x.replace('-',' ')}</button>)}</nav>{error&&<div className="error">{error}</div>}{content}</main>;
}
